# RBAC Constraints
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - block-default-sa.yaml
  - block-wildcard-rbac.yaml
  - block-cluster-admin.yaml
  - block-anonymous-cluster-admin.yaml
  # Uncomment for stricter SA token management
  # - block-automount-sa-token.yaml

