apiVersion: v1
kind: ConfigMap
metadata:
  name: nutanix-ai-config-overrides
  namespace: dm-dev-workspace
data:
  values.yaml: |
    # Use nai-operators-secret (deployed via CRS to workload clusters) for image pull
    imageCredentials:
      name: nai-operators-secret
