apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: clusterops-project-applications
  namespace: dm-nkp-gitops
spec:
  dependsOn:
    # Wait for project namespaces to be created by the Workspace controller
    - name: clusterops-project-definitions
  interval: 5s
  retryInterval: 30s
  path: ./kustomizations/project-applications
  prune: true
  sourceRef:
    kind: GitRepository
    name: gitops-demo
    namespace: kommander

