apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: clusterops-workspace-networkpolicies
  namespace: kommander
spec:
  dependsOn:
    - name: clusterops-workspaces
      namespace: kommander
  interval: 5s
  path: ./kustomizations/workspace-networkpolicies
  prune: true
  sourceRef:
    kind: GitRepository
    name: gitops-demo
    namespace: kommander
