apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # NDK
  - ndk
  # DISABLED: Nutanix AI dependencies (must be deployed before nutanix-ai)
  # - nutanix-ai-dependencies
  # Nutanix AI
  - nutanix-ai
