apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../resources/workspaces/batcave/projects
- ../../resources/workspaces/oscorp/projects
- ../../resources/workspaces/dm-dev-workspace/projects