apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # VirtualGroups for all users/groups
  - virtualgroups.yaml
  # Global-level role bindings
  - global-admin-rolebinding.yaml

