apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../bases/dm-nkp-workload-1.yaml
  - ../../bases/dm-nkp-workload-2.yaml
  # Sealed secrets are now applied via separate clusterops-sealed-secrets kustomization

patches:
  - path: dm-nkp-workload-1-patch.yaml
  - path: dm-nkp-workload-2-patch.yaml
