apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - dm-dev-workspace-superheros-rolebinding.yaml
  # Workspace Admin bindings for dm-dev-workspace-admin
  - dm-dev-workspace-admin-rolebindings.yaml
