apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Nutanix AI Dependencies
# These AppDeployments must be deployed before Nutanix AI 2.5.0

resources:
  - kserve-0.15.0.yaml
  - envoy-gateway-1.5.0.yaml
  - opentelemetry-operator-0.93.0.yaml

