apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Nutanix AI Dependencies
# These AppDeployments must be deployed before Nutanix AI 2.5.0

resources:
  - kserve.yaml
  - envoy-gateway.yaml
  - envoy-gatewayclass.yaml  # GatewayClass required for NAI - not created by Helm chart
  - opentelemetry-operator.yaml
