apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Sealed secrets for dm-nkp-workload-2
# These secrets are deployed inside the workload cluster

resources:
  - ndk-image-pull-sealed-secret.yaml

