apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Per-cluster sealed secrets (PC, CSI, Konnector, image registry)
  - dm-nkp-workload-1-sealed-secrets.yaml
  - dm-nkp-workload-2-sealed-secrets.yaml

