apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - vault-namespace.yaml
  - vault.yaml
  - vault-unseal-keys-sealed-secret.yaml
  - vault-kyverno-exception.yaml
  # Temporarily disabled due to Kyverno webhook issue
  # - vault-auto-unseal-job.yaml

