apiVersion: v1
kind: ConfigMap
metadata:
  name: nutanix-ai-2.5.0-config-overrides
  namespace: dm-dev-workspace
data:
  values.yaml: |
    imageCredentials:
      name: nutanix-ai-image-registry-credentials
