apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - dm-nkp-gitops-catalog-applications
  - nkp-nutanix-products-catalog-applications
  # DISABLED: platform-applications (all apps disabled - kube-prometheus-stack, rook-ceph, rook-ceph-cluster)
  # - platform-applications
