apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - project-grafana-loki.yaml
  - project-grafana-loki-overrides-configmap.yaml
  - project-grafana-loki-memory-alerts.yaml

