apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- nutanix-infra/overlays/2.17.0
  # Kubemark cluster for performance testing (CAPK provider must be installed)
  - kubemark-infra

