apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Nutanix Infrastructure Clusters
  - nutanix-infra/overlays/2.17.0
  
  # Docker Infrastructure Clusters (CAPD + Kubemark)
  - docker-infra
