apiVersion: v1
kind: ConfigMap
metadata:
  name: ndk-2.0.0-config-overrides
  namespace: dm-dev-workspace
data:
  values.yaml: |
    imageCredentials:
      name: ndk-image-pull-secret
      credentials:
        registry: https://index.docker.io/v1/
        username: <YOUR_DOCKER_USERNAME>
        password: <YOUR_DOCKER_PASSWORD>
        email: <YOUR_EMAIL>
