apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: clusterops-workspaces
  namespace: dm-nkp-gitops
spec:
  interval: 5s
  path: ./kustomizations/workspaces
  prune: true
  sourceRef:
    kind: GitRepository
    name: gitops-demo
    namespace: kommander

