apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Dependencies for nkp-insights (deploy these first)
  - kube-prometheus-stack
  - cloudnative-pg
  # harbor (depends on cloudnative-pg)
  - harbor
  # NKP Insights (depends on prometheus and cloudnative-pg)
  - nkp-insights
  # Logging stack (Fluent Bit log collector + Loki log aggregation + Grafana Logging dashboard)
  - fluent-bit
  - grafana-loki
  - grafana-logging
