apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Applications from dm-nkp-gitops-app-catalog for management cluster
  # - kyverno  # Disabled - causing webhook issues blocking Thanos/prometheus-adapter
  - kubescape-operator
  - kro
  - vault
